[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
stake_stepper = "YourProgramIDHere"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"